### ISSUE TITLE
Couple UI bugs on demo

### ISSUE THREAD

**Issue by shershen08** [sc0Vu/vuethexplore#27]
- notification items don't disappear after considerable time
- network selection list is not closed after selection

![screen shot 2018-05-15 at 17 28 38](https://user-images.githubusercontent.com/1363772/40066925-74a16780-5865-11e8-84b5-c96abe9dff7c.png)
![screen shot 2018-05-15 at 17 28 20](https://user-images.githubusercontent.com/1363772/40066926-74bcb9f4-5865-11e8-8a08-c9e87b742832.png)

**Comment by sc0Vu** [comment]
Hi @shershen08, I'll try to fix these, thanks!
